#cloud-config

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

write_files:
  - path: /opt/docker-compose.yml
    content: |
      version: '3.8'
      services:
        postgres:
          image: postgres:16
          container_name: postgres_db
          restart: always
          environment:
            POSTGRES_DB: vetclinicdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${db_password}
            PGDATA: /var/lib/postgresql/data/pgdata
          volumes:
            - postgres_data:/var/lib/postgresql/data
          ports:
            - "5432:5432"
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d vetclinicdb"]
            interval: 10s
            timeout: 5s
            retries: 5
          networks:
            - postgres_net

      volumes:
        postgres_data:
          driver: local

      networks:
        postgres_net:
          driver: bridge

runcmd:
  - curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  - sh /tmp/get-docker.sh
  - systemctl enable docker
  - systemctl start docker
  
  - mkdir -p /var/lib/postgresql/data
  - chmod 755 /var/lib/postgresql/data
  
  - cd /opt
  - docker compose up -d
  
  - sleep 15
  - docker ps
  - docker logs postgres_db
  
  - docker exec postgres_db pg_isready -U postgres -d vetclinicdb || echo "PostgreSQL not ready yet"
